// <auto-generated />
using APIFutebol.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFutebol.Migrations
{
    [DbContext(typeof(FutebolContext))]
    [Migration("20220709042341_Relacionando resultado e confronto")]
    partial class Relacionandoresultadoeconfronto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APIFutebol.Models.Confronto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Campeonato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChutesAGol_Time1")
                        .HasColumnType("int");

                    b.Property<int>("ChutesAGol_Time2")
                        .HasColumnType("int");

                    b.Property<string>("Estadio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicoPresente")
                        .HasColumnType("int");

                    b.Property<string>("Times")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Confrontos");
                });

            modelBuilder.Entity("APIFutebol.Models.Localizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("APIFutebol.Models.Resultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ConfrontoId")
                        .HasColumnType("int");

                    b.Property<int>("Placar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfrontoId")
                        .IsUnique();

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("APIFutebol.Models.Resultado", b =>
                {
                    b.HasOne("APIFutebol.Models.Confronto", "Confronto")
                        .WithOne("Resultado")
                        .HasForeignKey("APIFutebol.Models.Resultado", "ConfrontoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Confronto");
                });

            modelBuilder.Entity("APIFutebol.Models.Confronto", b =>
                {
                    b.Navigation("Resultado")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
